'use client';
import {useState,useEffect,type CSSProperties} from 'react';
import geography from '../public/maps/geography.json';
import {ArrowUpRight,ArrowRight,ShieldCheck,Compass,Flag,Download,Check,Shuffle,Globe2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const cities=[{name:'Tokyo',ko:'도쿄',flag:'🇯🇵'},{name:'Seoul',ko:'서울',flag:'🇰🇷'},{name:'Busan',ko:'부산',flag:'🇰🇷'},{name:'Paris',ko:'파리',flag:'🇫🇷'}];
const cityKeys=['tokyo','seoul','busan','paris'] as const;
const avatars=['토끼','마법사','고양이','병아리','우주인','유령'];
function PixelAvatar({index}:{index:number}){return <span role="img" aria-label={avatars[index]} className="pixelavatar" style={{backgroundPosition:`${(index%3)*50}% ${Math.floor(index/3)*100}%`}}/>}
const dots=[{x:18,y:25,a:1},{x:48,y:19,a:3},{x:76,y:28,a:5},{x:33,y:46,a:0},{x:64,y:48,a:4},{x:17,y:69,a:2},{x:46,y:75,a:5},{x:79,y:75,a:3}];
const today=()=>new Date().toLocaleDateString('en-CA');
type Trip={city:number,avatar:number,start:string,end:string,checks:number,last:string,ended:boolean};
export default function Home(){
 const [trip,setTrip]=useState<Trip|null>(null);const [ready,setReady]=useState(false);const [modal,setModal]=useState('');const [city,setCity]=useState(0);const [avatar,setAvatar]=useState(0);const [start,setStart]=useState(today());const [end,setEnd]=useState(()=>{let d=new Date();d.setDate(d.getDate()+5);return d.toLocaleDateString('en-CA')});const [selected,setSelected]=useState(0);const [reactions,setReactions]=useState<Record<string,string>>({});const [notice,setNotice]=useState('');const [spark,setSpark]=useState(false);
 useEffect(()=>{try{let v=localStorage.getItem('solo-dot-trip');if(v){const t=JSON.parse(v);if(t.end<today())t.ended=true;setTrip(t);setCity(t.city)}const r=localStorage.getItem('solo-dot-reactions');if(r)setReactions(JSON.parse(r))}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready){try{if(trip)localStorage.setItem('solo-dot-trip',JSON.stringify(trip));localStorage.setItem('solo-dot-reactions',JSON.stringify(reactions))}catch{}}},[trip,reactions,ready]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t)},[notice]);
 const c=cities[city];const mapKey=cityKeys[city];const geo=geography[mapKey];
 const dotStyle=(index:number):CSSProperties=>({'--dot-x':geo.wide.dots[index][0]+'%','--dot-y':geo.wide.dots[index][1]+'%','--dot-x-mobile':geo.tall.dots[index][0]+'%','--dot-y-mobile':geo.tall.dots[index][1]+'%'} as CSSProperties);
const active=!!trip&&trip.city===city&&!trip.ended&&trip.start<=today()&&trip.end>=today();const days=trip?Math.max(1,Math.floor((Date.now()-new Date(trip.start+'T00:00:00').getTime())/86400000)+1):1;
 function checkin(){if(trip&&!trip.ended&&trip.city!==city){setCity(trip.city);setNotice('내 여행 도시로 돌아왔어요. 안부를 남겨주세요.');return}if(!active){setModal('trip');return}if(trip!.last===today()){setNotice('오늘의 생존신고를 이미 남겼어요. 내일 또 만나요!');return}setTrip({...trip!,checks:trip!.checks+1,last:today()});setSpark(true);setNotice('✨ 오늘도 살아있음! 지도에 작은 반짝임을 남겼어요.');setTimeout(()=>setSpark(false),2500)}
 return <main><header className="topbar"><a className="brand" href="/">SOLO<span>DOT</span><i/></a><span className="tagline">혼자여도, 어딘가 함께.</span><span className="demo"><i/> INTERACTIVE DEMO</span></header>
 <div className="workspace"><aside className="rail"><div><div className="eyebrow">YOUR LITTLE WORLD</div><h1>지금, 우리는<br/>여행 중<span>.</span></h1><p className="intro">같은 도시, 각자의 여행.<br/>작은 점으로 안부를 전해요.</p></div><div className="mytrip"><div className="sectionlabel">MY TRIP <Compass size={16}/></div><div className="tripavatar"><PixelAvatar index={trip?.avatar??avatar}/></div><h2>{trip?`${cities[trip.city].flag} ${cities[trip.city].name}`:'나의 여행을 시작해요'}</h2><p>{trip?`${trip.start} — ${trip.end}`:'어디를 혼자 여행 중인가요?'}</p>{trip&&<span className="daypill">{trip.ended?'무사히 돌아왔어요':active?`DAY ${days} · 여행 중`:'출발을 기다리는 중'}</span>}<button className="primary" onClick={()=>{if(trip)setCity(trip.city);setModal(trip?(trip.ended?'summary':'mytrip'):'trip')}}>{trip?'나의 여행 보기':'여행 등록하기'}<ArrowUpRight size={18}/></button></div><div className="quiet"><ShieldCheck size={21}/><div><strong>가까움의 적당한 거리</strong><p>이름도, 정확한 위치도 없이.<br/>서로의 존재만 느껴요.</p></div></div><div className="railbottom">Connection without relationship.<span>SOLO DOT © 2026</span></div></aside>
 <section className="mainarea"><div className="mapheading"><div><div className="eyebrow">SOMEWHERE IN</div><h2>{c.name}<span>{c.flag}</span></h2></div><div className="cityactions"><span className="cityko">{c.ko}의 작은 여행자들</span><button className="outline" onClick={()=>setModal('city')}><Globe2 size={17}/> 도시 둘러보기</button></div></div><div className="map"><picture className="geographic-map"><source media="(max-width:700px)" srcSet={`/maps/${mapKey}-tall.png`}/><img src={`/maps/${mapKey}-wide.png`} width={240} height={160} alt={`${c.ko}의 실제 육지·도심·주요 하천을 단순화한 도트 지도`}/></picture><div className="mapbadge"><i/> {8+(active?1:0)}개의 도트 <span>· 데모 여행자</span></div><div className="city-map-label" aria-hidden="true"><strong>{c.name.toUpperCase()}</strong><span>{c.ko}</span></div>{dots.map((d,i)=><button key={i} className="dot" style={dotStyle(i)} aria-label={`${avatars[d.a]} 여행자 보기`} onClick={()=>{setSelected(i);setModal('person')}}><span><PixelAvatar index={d.a}/></span>{i===3&&<small>🍀 좋은 여행!</small>}{i===1&&<em/>}</button>)}{active&&<button className={'dot own '+(spark?'spark':'')} style={dotStyle(8)} onClick={()=>setModal('mytrip')} aria-label="나의 도트"><span><PixelAvatar index={trip!.avatar}/></span><small>{spark?'✨ 나 살아있음!':'나의 작은 점'}</small></button>}<div className="mapfooter"><ShieldCheck size={14}/> 캐릭터는 실제 위치와 관계없는 가상의 위치에 있어요.</div><a className="map-source" href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">지도 데이터: Natural Earth · 단순화</a><div className="compass">N<br/>↑</div></div>
 <div className="belowmap"><div><span className="livepulse"/><strong>혼자 여행하는 누군가가, 여기에도.</strong><p>도트를 눌러 작은 응원을 보내보세요.</p></div><button className={'checkin '+(trip?.last===today()?'checked':'')} onClick={checkin}>{trip?.last===today()?<Check size={20}/>:<span>✦</span>}{trip?.last===today()?'오늘의 안부를 남겼어요':'나 살아있음!'}<ArrowRight size={18}/></button></div><div className="footnote"><span>👋 말하지 않아도 괜찮은 연결</span><span>다른 도트는 가상 여행자예요 · 내 여행은 이 기기에 저장돼요</span></div></section></div>
 <Dialog open={!!modal} onOpenChange={o=>{if(!o)setModal('')}}><DialogContent className="flowmodal"><DialogTitle className="modaltitle">{({trip:'어디를 혼자 여행 중인가요?',avatar:'이번 여행의 나는',city:'어느 도시가 궁금한가요?',person:'어딘가의 여행자',mytrip:'나의 작은 여행',summary:'여행이 한 장의 기억으로'} as Record<string,string>)[modal]}</DialogTitle><DialogDescription>{modal==='trip'?'도시와 날짜만 알려주세요. GPS는 필요 없어요.':modal==='avatar'?'이름 대신, 마음에 드는 작은 모습을 골라요.':modal==='person'?'서로를 몰라도, 좋은 여행을 빌어줄 수 있어요.':modal==='summary'?'무사히 돌아왔습니다. 다음 여행에서 또 만나요.':'정확한 위치는 수집하거나 공유하지 않아요.'}</DialogDescription>
 {(modal==='trip'||modal==='city')&&<><div className="cities">{cities.map((v,i)=><button key={v.name} className={city===i?'selected':''} onClick={()=>setCity(i)}><span>{v.flag}</span><b>{v.name}</b><small>{v.ko}</small>{city===i&&<Check size={18}/>}</button>)}</div>{modal==='trip'?<form onSubmit={e=>{e.preventDefault();setModal('avatar')}}><div className="dates"><label>출발일<input type="date" required value={start} onChange={e=>{setStart(e.target.value);if(end<e.target.value)setEnd(e.target.value)}}/></label><label>돌아오는 날<input type="date" required min={start>today()?start:today()} value={end} onChange={e=>setEnd(e.target.value)}/></label></div><button className="primary">다음 · 나의 모습 고르기<ArrowRight size={18}/></button></form>:<button className="primary" onClick={()=>{setModal('')}}>지도 둘러보기<ArrowRight size={18}/></button>}</>}
 {modal==='avatar'&&<><div className="avatargrid">{avatars.map((v,i)=><button aria-label={`${v} 선택`} aria-pressed={avatar===i} className={avatar===i?'selected':''} onClick={()=>setAvatar(i)} key={v}><PixelAvatar index={i}/></button>)}</div><button className="textbutton" onClick={()=>setAvatar(Math.floor(Math.random()*6))}><Shuffle size={16}/> 운명에 맡기기</button><button className="primary" onClick={()=>{setTrip({city,avatar,start,end,checks:0,last:'',ended:false});setReactions({});setModal('');setNotice('지도에 나의 작은 점이 생겼어요. 좋은 여행!')}}>이 모습으로 여행 시작<ArrowRight size={18}/></button><button className="textbutton" onClick={()=>setModal('trip')}>← 날짜 다시 고르기</button></>}
 {modal==='person'&&<><div className="profileavatar"><PixelAvatar index={dots[selected].a}/></div><div className="profiletitle">{c.name.toUpperCase()} <span>DAY {selected%5+1}</span></div><p className="center muted">✓ {selected%3+1}시간 전 생존신고 · 가상 여행자</p><div className="reactions">{['👋','🍀','❤️'].map(e=><button key={e} disabled={!!reactions[`${c.name}-${selected}`]} onClick={()=>{setReactions({...reactions,[`${c.name}-${selected}`]:e});setNotice(`${e} 작은 응원을 보냈어요. (데모)`)}}><span>{e}</span>{reactions[`${c.name}-${selected}`]===e?'보냈어요':'보내기'}</button>)}</div><p className="center muted">누가 보냈는지는 전하지 않아요.</p></>}
 {modal==='mytrip'&&trip&&<><div className="profileavatar"><PixelAvatar index={trip.avatar}/></div><div className="profiletitle">{c.name.toUpperCase()} <span>DAY {days}</span></div><p className="center muted">{trip.start} — {trip.end}</p><div className="statrow"><span>남긴 생존신고</span><strong>{trip.checks}번</strong></div><button className="primary" onClick={()=>{checkin();setModal('')}}>✨ 오늘의 안부 남기기</button><button className="textbutton" onClick={()=>{setTrip({...trip,ended:true});setModal('summary')}}><Flag size={16}/> 여행 마치고 기록 카드 만들기</button></>}
 {modal==='summary'&&trip&&<><div className="souvenir"><div className="eyebrow">A LITTLE MEMORY FROM</div><h2>{c.name.toUpperCase()} {c.flag}</h2><div className="profileavatar"><PixelAvatar index={trip.avatar}/></div><strong className="tripdays">{Math.max(1,Math.min(days,Math.round((new Date(trip.end).getTime()-new Date(trip.start).getTime())/86400000)+1))} DAYS</strong><div className="statrow"><span>생존신고</span><b>{trip.checks}</b></div><p>무사히 돌아왔습니다.</p><div className="brand">SOLO<span>DOT</span></div></div><button className="primary" onClick={async()=>{const sprite=new Image();sprite.src='/pixel-avatars.png';try{await sprite.decode()}catch{setNotice('이미지를 불러오지 못했어요. 다시 시도해주세요.');return}const canvas=document.createElement('canvas');canvas.width=720;canvas.height=960;const x=canvas.getContext('2d')!;x.fillStyle='#edf2dc';x.fillRect(0,0,720,960);x.textAlign='center';x.fillStyle='#23483b';x.font='bold 48px sans-serif';x.fillText(c.name.toUpperCase()+' '+c.flag,360,150);x.imageSmoothingEnabled=false;const sw=sprite.naturalWidth/3,sh=sprite.naturalHeight/2;x.drawImage(sprite,(trip.avatar%3)*sw,Math.floor(trip.avatar/3)*sh,sw,sh,260,210,200,200);x.font='bold 42px sans-serif';x.fillText('생존신고 '+trip.checks+'번',360,520);x.font='26px sans-serif';x.fillText(trip.start+' — '+trip.end,360,600);x.fillText('무사히 돌아왔습니다.',360,720);x.font='bold 28px monospace';x.fillText('SOLO DOT',360,850);const a=document.createElement('a');a.download='solo-dot-'+c.name+'.png';a.href=canvas.toDataURL();a.click()}}><Download size={18}/> 기억 카드 저장하기</button><button className="textbutton" onClick={()=>setModal('trip')}>새로운 여행 시작하기 →</button></>}
 </DialogContent></Dialog>{notice&&<div className="toast" role="status">{notice}</div>}</main>
}
